version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel_login
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      # Remove node_modules volume for backend as well
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_login
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel123
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "8000:8000"

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Keep this to use container's node_modules
    environment:
      - REACT_APP_API_URL=https://localhost/api
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge